spring.application.name=song-service
server.port=8072
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/song-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
