spring.application.name=resource-service
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/resource-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
song-service.url=http://localhost:8081
