spring.application.name=resource-service
server.port=8071
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/resource-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
song-service.url=${SONG_SERVICE_URL:http://localhost:8072}

# Frequency of heartbeats sent by the client to the server
eureka.instance.lease-renewal-interval-in-seconds=5
# Frequency of registry data retrieval from the server to the client's local cache
eureka.client.registry-fetch-interval-seconds=5
